In [ ]:
x = [10,20,30,40,50,60]
print(x)

In [ ]:
print(x[1])

In [ ]:
x[1:5:2]

In [ ]:
import numpy as np

y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(y[0,1])

2


In [ ]:
z = np.array([[[1,2,3],[2,4,5],[5,6,7]],[[2,5,4],[2,6,5],[5,6,5]],[[3,6,6],[4,6,5],[8,5,5]]])
print(z)

[[[1 2 3]
  [2 4 5]
  [5 6 7]]

 [[2 5 4]
  [2 6 5]
  [5 6 5]]

 [[3 6 6]
  [4 6 5]
  [8 5 5]]]


In [ ]:
y[0,2]

3

In [ ]:
y = np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
y[0,:]
print(y[0,:])

[1 2 3]


In [ ]:
print(y[:,0])

[1 4]


In [ ]:
from pylab import *

y = sin(x)
plot(x,y)
xlabel('This is x-axis')
ylabel('This is y-axis')
title('This is the title')

z = cos(x)
plot(x,z,'r')

In [ ]:
site = 'gfg'
yourName = 'wajahat'
    
if site == 'gfx':  
  print('Logging on to geeksforgeeks...')
  print('Tab is important in python')
  if  yourName=='wajahat':
     print('This is nested if')
else:  
    print('retype the URL.')
    print('Tab is not imp in matlab')  
print('All set !') 

In [ ]:
site = 'gfg'
yourName = 'wajahat'
    
if site == 'gfx': 
   print('Logging on to geeksforgeeks...')
   print('Tab is important in python')
if  yourName=='wajahat':
     print('This is nested if')
else:  
    print('retype the URL.')
    print('Tab is not imp in matlab')  
print('All set !') 

In [ ]:
y =[10,20,3,4,-5]
for i in y:
  print(i)
print(y)

10
20
3
4
-5
[10, 20, 3, 4, -5]


In [ ]:
def my_add(x,y):
  c = x + y
  d = x*y
  return c,y

In [ ]:
a,b = my_add(3,4)
print(a)
print(b)

7
4


In [ ]:
print(my_add(3,4))

(7, 4)


In [ ]:
x = np.array([1,2,3,4,5])
dumx = [2*i for i in x if i>2]
print(dumx)

[6, 8, 10]


In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print(x.reshape(2,-1))

[[1 2 3]
 [4 5 6]]


Good examples of reshaping https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

In [ ]:
a = np.arange(6)
print(a)

print(a.reshape((3, 2)))

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
np.reshape(a, (2, 3), order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a = np.arange(6).reshape((3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.reshape(a, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
x = np.random.randn(4, 3, 2, 2)
#print(x)
#print(x[1])

y = x[1].copy()
z=y.flatten()
print(z)
print(z.shape)

[-0.81497352  0.40876245  0.23407873 -0.59346759 -0.23628579 -0.20230445
 -0.43976482  0.02656888 -1.61221444  0.31207507  1.12111517  0.40902655]
(12,)


In [ ]:
import numpy as np

a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

In [ ]:
print(a3)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [ ]:
print(a3[2,:,:])

[[30 31 32]
 [33 34 35]
 [36 37 38]]


Very good pictorial description at https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/


```
# This is formatted as code
```



In [ ]:
print(a3[:, 1, 2])

[15 25 35]


In [ ]:
print(a3[0, :, 1])

[11 14 17]


In [ ]:
print(a3[1, 2])

[26 27 28]


In [ ]:
print(a3[2, 0, 1])

31


In [ ]:
print(a3[:, 1])

In [ ]:
print(a3[:, :, 0])

In [ ]:
print(a3[:2,1:,:2])

In [ ]:
print(a3[:,::2,::2])