# ML Lab 3

In [ ]:
x = [10,20,30,40,50,60]
print(x)

[10, 20, 30, 40, 50, 60]


In [ ]:
print(x[-1])

60


In [ ]:
x[1:5:2]

[20, 40]

In [ ]:
import numpy as np

x = np.arange(1,8)
print(x)

[1 2 3 4 5 6 7]


In [ ]:
import numpy as np

y = np.arange(1,11,2)
print(y)

x = np.arange(9,0,-2)
x = np.delete(x,1)
print(x)

[1 3 5 7 9]
[9 5 3 1]


# ML Lab 4

In [ ]:
x = []